sudo: required
cache:
  directories:
    - node_modules

group: bluezone

env:
  global:
    - org="automated-test"
    - cat="sb"
    - OCTOKIT_API_ENDPOINT: https://github.ibm.com/api/v3/
  matrix:
    - policyDir="." policyName="mqinvoke"


language: node_js
node_js:
  - "4"

before_install:
  - npm install apiconnect --no-optional
  - mkdir tmp || true
  - mkdir out || true
  - chmod 755 ./build.sh

script:
  - ./build.sh $policyDir $policyName

before_deploy:
  - mkdir  ~/.apiconnect/
  - ./node_modules/.bin/apic  --disable-analytics --accept-license
  - ./node_modules/.bin/apic login -s apimdev2017.hursley.ibm.com -u  chris.phillips@uk.ibm.com -p \!n0r1t5@C
  - ./node_modules/.bin/apic policies:publish --directory tmp/$policyName --catalog $cat --organization $org --server apimdev2017.hursley.ibm.com
  - tar cvfz out/apic_log.tar.gz ~/.apiconnect/
  - rm -rf node_modules

deploy:
  provider: releases
  file_glob: true
  file: out/*
  api_key: "b1249343c36b9cfd5dfbecdb84ee4984c784922d"
  skip_cleanup: true
  on:
    branch: master
